# Site settings
title: Todor Genov - Technology Consulting
subtitle: Distributed Systems, Scalability, System Reliability, MLOps, DevSecOps
description: Technology consulting specializing in distributed systems, scalability, system reliability, MLOps, and DevSecOps. Expert guidance for modern software architecture and infrastructure.
author: Todor Genov
email: consulting@subnet.co.za
url: https://todor.github.io/www.subnet.co.za
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE
  - CHANGELOG.md
  - vendor/
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Include files
include:
  - .htaccess

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Todor Genov"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Feed settings
feed:
  path: atom.xml

# SEO settings
twitter:
  username: todorgenov
linkedin:
  username: todor-genov

# GitHub Pages settings
github: [metadata]